// This file contains all actions triggered on the app related to the app state

// GENERAL
export const LOGOUT = 'LOGOUT';

// AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// SESSION
export const SESSION_UPDATE = 'SESSION_UPDATE';

// TASKS

// GET LISTS
export const TASK_LISTS_REQUEST = 'TASK_LISTS_REQUEST';
export const TASK_LISTS_RECEIVED = 'TASK_LISTS_RECEIVED';
export const TASK_LISTS_REQUEST_ERROR = 'TASK_LISTS_REQUEST_ERROR';

// DELETE LIST
export const TASK_LISTS_DELETE_LIST = 'TASK_LISTS_DELETE_LIST';
export const TASK_LISTS_DELETE_LIST_ERROR = 'TASK_LISTS_DELETE_LIST_ERROR';

// RENAME LIST
export const TASK_LISTS_UPDATE_LIST = 'TASK_LISTS_UPDATE_LIST';
export const TASK_LISTS_UPDATE_LIST_ERROR = 'TASK_LISTS_UPDATE_LIST_ERROR';

// CREATE LIST
export const TASK_LISTS_CREATE_LIST = 'TASK_LISTS_CREATE_LIST';
export const TASK_LISTS_CREATE_LIST_ERROR = 'TASK_LISTS_CREATE_LIST_ERROR';

// CHANGE LIST (show tasks from a list)
export const TASK_LISTS_CHANGE_LIST = 'TASK_LISTS_CHANGE_LIST';
export const TASK_LISTS_CHANGE_LIST_ERROR = 'TASK_LISTS_CHANGE_LIST_ERROR';

// GET TASKS (for one list)
export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_RECEIVED = 'TASKS_RECEIVED';
export const TASKS_REQUEST_ERROR = 'TASKS_REQUEST_ERROR';

// CREATE TASK
export const TASKS_CREATE_TASK = 'TASKS_CREATE_TASK';
export const TASKS_CREATE_TASK_ERROR = 'TASKS_CREATE_TASK_ERROR';

// DELETE TASK
export const TASKS_DELETE_TASK = 'TASKS_DELETE_TASK';
export const TASKS_DELETE_TASK_ERROR = 'TASKS_DELETE_TASK_ERROR';

// EDIT TASK
export const TASKS_EDIT_TASK = 'TASKS_EDIT_TASK';
export const TASKS_EDIT_TASK_ERROR = 'TASKS_EDIT_TASK_ERROR';
